name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Setup JVM and Scala tools
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt sbtn

      - name: Scalafmt Check
        run: sbtn scalafmtCheckAll

      - name: Compile
        run: sbtn compile

      - name: Run Tests
        run: sbtn test
